# This file is a template, and might need editing before it works on your project.
# use the official gcc image, based on debian
# can use verions as well, like gcc:5.2
# see https://hub.docker.com/_/gcc/
image: gcc

build:
  stage: build
  before_script:
     - apt update && apt -y install make autoconf cmake
     # Qt5 download.
     - apt -y install qtcreator
     - apt -y install qt5-default
  script:
    # Build methods, and tests.
    - ./build.sh
    # Build gui app.
    - qmake -o Makefile bounds.pro
    - make -j9
  artifacts:
    paths:
      - bin/

# run tests using the binary built before
method-tests:
  stage: test
  script:
    - ./bin/circletest
    - ./bin/parallelTest
    - ./bin/rectangleTest
    - ./bin/equTriantest
    - ./bin/squareTest
