# This file is a template, and might need editing before it works on your project.
# use the official gcc image, based on debian
# can use verions as well, like gcc:5.2
# see https://hub.docker.com/_/gcc/
image: gcc

build:
  stage: build
  before_script:
     - apt update && apt -y install make autoconf cmake
     # Qt5 download.
     - apt -y install qtcreator
     - apt -y install qt5-default

  script:
    # Build methods, and tests.
    - ./build.sh
    # Build Debug gui app.
    - ./buildGui.sh
    # Build Release gui app.
    - ./buildGuiRelease.sh
  artifacts:
    paths:
      - bin/

# run tests using the binary built before
method-tests:
  stage: test
  script:
    - ./runTests.sh
